### ISSUE TITLE
A duplicated tracker is created when retrying ProductDiscussionRequest

### ISSUE THREAD

**Issue by chytonpide** [VaughnVernon/IDDD_Samples#44]
A duplicated tracker is created when retrying ProductDiscussionRequest.

- `ProductApplicationService.retryProductDiscussionRequest()` calls `Product.requestDiscussion()`.
- `Product.requestDiscussion()` publish `ProductDiscussionRequested` event.
- the listener calls `ProductApplicationService.startDiscussionInitiation()`.

and then, the `ProductApplicationService.startDiscussionInitiation()` creates the tracker again even though a retry has been requested by an existing tracker.
I think it is needed to add the logic that creating a tracker only when the `Product` doesn't have `discussionInitiation`.

```
public void startDiscussionInitiation(StartDiscussionInitiationCommand aCommand) {
  ...
  if(product.discussionInitiationId() == null) {
    ...create new tracker
  }
  ...
}
```

**Comment by VaughnVernon** [comment]
Thanks, @chytonpide. I see the problem.

There's a bit more to this fix. If the tracker already exists then we have to get it to uses its `processId` to initiate the discussion. It could use a method composition since `startDiscussionInitiation()` will be doing too much by adding it in. I suggest a private method to return a tracker that's either new or preexisting based on attempted get from it's repository.

Would you like to contribute this in a PR for my review?

**Comment by chytonpide** [comment]
@VaughnVernon Thanks for giving me a chance to contribute to this.
I will make the PR by March 31.
